- hosts: qiita-stocker-backend
  become: yes
  roles:
    - common
    - mysql
    - php
    - php-fpm
    - nginx
    - composer
    - aws-codedeploy-agent
    - aws-scripts-mon
    - qiita-stocker-backend
