- name: Download CloudWatchMonitoringScripts
  get_url:
    url: http://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.2.zip
    dest: /opt

- name: unzip CloudWatchMonitoringScripts.zip
  unarchive: src=/opt/CloudWatchMonitoringScripts-1.2.2.zip remote_src=yes dest=/opt/
