- name: Set cron-tab
  cron:
    name: "mon-put-instance-data.pl"
    minute: "*/5"
    user: "{{ app_user }}"
    job: "/opt/aws-scripts-mon/mon-put-instance-data.pl --mem-used-incl-cache-buff --mem-util --mem-used --mem-avail --disk-space-util --disk-path=/ --from-cron"
