- name: Install Official MySQL Repository
  yum: name=https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm

- name: Disable MySQL 8.0 Repository
  shell: yum-config-manager --disable mysql80-community

- name: Enable MySQL 5.6 Repository
  shell: yum-config-manager --enable mysql56-community

- name: Install MySQL5.6 Client
  yum : name={{ item }} enablerepo=mysql56-community state=latest
  with_items:
    - mysql-community-client
