- name: Install Official MySQL Repository
  yum: name=https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm

- name: Disable MySQL 8.0 Repository
  shell: yum-config-manager --disable mysql80-community

- name: Enable MySQL 5.7 Repository
  shell: yum-config-manager --enable mysql57-community

- name: Install MySQL5.7 Client
  yum : name=mysql-community-client enablerepo=mysql57-community state=latest
